
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author leonardo
 */
public class Luz extends javax.swing.JFrame {
int ri, rf, kvh;
String nom, dir;
float tp;
    /**
     * Creates new form Luz
     */
    public Luz() {
        initComponents();
        this.setSize(577,542);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    DecimalFormat r=new DecimalFormat("#.##");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Nombre del cliente:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 140, 240, 40);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Dirección:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 220, 120, 40);

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Registro Inicial:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 290, 200, 40);

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Registro Final:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 370, 170, 40);

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("EMPRESA PATITO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 20, 240, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PATITO.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 10, 100, 90);

        t1.setBackground(new java.awt.Color(153, 0, 153));
        t1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(240, 140, 190, 40);

        t2.setBackground(new java.awt.Color(153, 0, 153));
        t2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(210, 220, 360, 40);

        t4.setBackground(new java.awt.Color(153, 0, 153));
        t4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(t4);
        t4.setBounds(210, 370, 220, 40);

        t3.setBackground(new java.awt.Color(153, 0, 153));
        t3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(t3);
        t3.setBounds(210, 290, 220, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 440, 580, 10);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/luz.png"))); // NOI18N
        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 450, 110, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escoba.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(500, 10, 30, 33);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/regresar.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(460, 10, 30, 33);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(540, 10, 30, 33);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/luz.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 580, 500);

        jMenu1.setText("Opciones");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/luz.png"))); // NOI18N
        jMenuItem1.setText("Crear");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escoba.png"))); // NOI18N
        jMenuItem2.setText("Limpiar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/regresar.png"))); // NOI18N
        jMenuItem3.setText("Regresar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x.png"))); // NOI18N
        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por utilizar el sistema");
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por utilizar el sistema");
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Escritorio().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Escritorio().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(t1.getText().isEmpty()||t2.getText().isEmpty()||t3.getText().isEmpty()||t4.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Datos Vacios","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            nom=t1.getText();
            nom=nom.toUpperCase();
            dir=t2.getText();
            dir.toUpperCase();
            ri=Integer.parseInt(t3.getText());
            if(ri<=0)
            {
                JOptionPane.showMessageDialog(null,"Solo puede ingresar numeros positivos","Registro inicial",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
             rf=Integer.parseInt(t4.getText());
            if(rf<=ri||rf<0||ri<0)
            {
                JOptionPane.showMessageDialog(null,"Los registros tienen que ser mayor a cero\nEl registro final tiene que ser menor al registro inicial","Error",JOptionPane.ERROR_MESSAGE);
                
            }
            else
            {
                kvh=rf-ri;
			//condicion1
			//140 kvh o menos 150 pesos
			if(kvh<=140)
			{
				tp=150;
			}
			//condicional 2
			//los siguientes 170 kvh 5.50 c/u
			if((kvh>140)&&kvh<=310)
			{
				tp=(float) (150+((kvh-140)*5.50));
			}
			if(kvh>310)
			{
				tp=(float) (150+(170*5.50)+((kvh-310)*3.50));
			}
                        ReciboLuz RL=new ReciboLuz();
                        RL.setVisible(true);
                        RL.l1.setText(nom.toString());
                        RL.l2.setText(dir.toString());
                        RL.l3.setText(Integer.toString(ri));
                        RL.l4.setText(Integer.toString(rf));
                        RL.l5.setText(Integer.toString(kvh));
                        RL.l6.setText(r.format(tp));
                        
            }   
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if(t1.getText().isEmpty()||t2.getText().isEmpty()||t3.getText().isEmpty()||t4.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Datos Vacios","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            nom=t1.getText();
            nom=nom.toUpperCase();
            dir=t2.getText();
            dir=dir.toUpperCase();
            ri=Integer.parseInt(t3.getText());
            if(ri<=0)
            {
                JOptionPane.showMessageDialog(null,"Solo puede ingresar numeros positivos","Registro inicial",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
             rf=Integer.parseInt(t4.getText());
            if(rf<=ri||rf<0)
            {
                JOptionPane.showMessageDialog(null,"nEl registro final tiene que ser mayor al registro inicial","Error",JOptionPane.ERROR_MESSAGE);
                
            }
            else
            {
                kvh=rf-ri;
			//condicion1
			//140 kvh o menos 150 pesos
			if(kvh<=140)
			{
				tp=150;
			}
			//condicional 2
			//los siguientes 170 kvh 5.50 c/u
			if((kvh>140)&&kvh<=310)
			{
				tp=(float) (150+((kvh-140)*5.50));
			}
			if(kvh>310)
			{
				tp=(float) (150+(170*5.50)+((kvh-310)*3.50));
			}
                        ReciboLuz RL=new ReciboLuz();
                        RL.setVisible(true);
                        RL.l1.setText(nom.toString());
                        RL.l2.setText(dir.toString());
                        RL.l3.setText(Integer.toString(ri));
                        RL.l4.setText(Integer.toString(rf));
                        RL.l5.setText(Integer.toString(kvh));
                        RL.l6.setText(r.format(tp));
                        
            }   
            }
            
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Luz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Luz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Luz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Luz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Luz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables
}
