
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ALUMNO
 */
public class Recibo extends javax.swing.JFrame {

    /**
     * Creates new form Recibo
     */
    public Recibo() {
        initComponents();
        this.setSize(650,523);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 255, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre del empleado:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 170, 170, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Numero de empleado:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 130, 170, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Puesto:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(420, 170, 60, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Salario Diario:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 210, 100, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Dias trabajados:");
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 120, 130, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Horas extras:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(380, 210, 100, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Faltas:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(420, 270, 70, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Salario Neto:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(370, 320, 130, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Impuestos retenidos:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 320, 210, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Seguro Medico:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(350, 370, 160, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Monto Horas Extras:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 370, 200, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Bono:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 270, 70, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel16.setText("Total a recibir:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 420, 260, 44);

        l13.setBackground(new java.awt.Color(255, 255, 255));
        l13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(l13);
        l13.setBounds(190, 130, 150, 20);

        l12.setBackground(new java.awt.Color(255, 255, 255));
        l12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(l12);
        l12.setBounds(190, 210, 90, 20);

        l11.setBackground(new java.awt.Color(255, 255, 255));
        l11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(l11);
        l11.setBounds(490, 120, 90, 20);

        l10.setBackground(new java.awt.Color(255, 255, 255));
        l10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(l10);
        l10.setBounds(490, 210, 90, 20);

        l9.setBackground(new java.awt.Color(255, 255, 255));
        l9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(l9);
        l9.setBounds(190, 170, 150, 20);

        l4.setBackground(new java.awt.Color(255, 255, 255));
        l4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(l4);
        l4.setBounds(210, 370, 120, 30);

        l7.setBackground(new java.awt.Color(255, 255, 255));
        l7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(l7);
        l7.setBounds(270, 420, 210, 50);

        l2.setBackground(new java.awt.Color(255, 255, 255));
        l2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(l2);
        l2.setBounds(510, 320, 130, 30);

        l5.setBackground(new java.awt.Color(255, 255, 255));
        l5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(l5);
        l5.setBounds(510, 370, 130, 30);

        l3.setBackground(new java.awt.Color(255, 255, 255));
        l3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(l3);
        l3.setBounds(510, 280, 90, 20);

        l6.setBackground(new java.awt.Color(255, 255, 255));
        l6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(l6);
        l6.setBounds(70, 270, 90, 20);

        l1.setBackground(new java.awt.Color(255, 255, 255));
        l1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(l1);
        l1.setBounds(210, 320, 120, 30);

        l8.setBackground(new java.awt.Color(255, 255, 255));
        l8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(l8);
        l8.setBounds(490, 170, 90, 20);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/regresar.png"))); // NOI18N
        jButton7.setToolTipText("regresar");
        jButton7.setDisabledSelectedIcon(null);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setOpaque(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(600, 10, 40, 30);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x.png"))); // NOI18N
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(560, 10, 40, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 92)); // NOI18N
        jLabel4.setText("Recibo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, -30, 270, 140);

        jSeparator1.setBackground(new java.awt.Color(255, 204, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 410, 650, 20);

        jSeparator2.setBackground(new java.awt.Color(255, 51, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 51, 0));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 260, 650, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p5.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 650, 470);

        jMenu1.setText("Opciones");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/regresar.png"))); // NOI18N
        jMenuItem2.setText("Regresar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x.png"))); // NOI18N
        jMenuItem1.setText("Cerrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por utilizar el sistema");
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por utilizar el sistema");
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ReciboPago2().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ReciboPago2().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recibo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    javax.swing.JLabel l1;
    javax.swing.JLabel l10;
    javax.swing.JLabel l11;
    javax.swing.JLabel l12;
    javax.swing.JLabel l13;
    javax.swing.JLabel l2;
    javax.swing.JLabel l3;
    javax.swing.JLabel l4;
    javax.swing.JLabel l5;
    javax.swing.JLabel l6;
    javax.swing.JLabel l7;
    javax.swing.JLabel l8;
    javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables
}
