/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ALUMNO
 */
import javax .swing.*;
import java.io.*;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
public class ReciboDePago extends javax.swing.JFrame {

    /**
     * Creates new form ReciboDePago
     */
    String nom, p, dato;
    int dt, f, het, ne;
    float sd, sn=0, mhe=0, tp=0, d=0, sm=0, bono=0, des=0;
    String[] dit={"0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15"}, pues={"Gerente","Despachador","Cajero","Limpiador"};
    DecimalFormat q=new DecimalFormat();
    private Object Interger;
    public ReciboDePago() {
        initComponents();
        this.setSize(610,700);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcular.png"))); // NOI18N
        jButton1.setToolTipText("Calcular");
        jButton1.setDisabledSelectedIcon(null);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 10, 30, 33);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x.png"))); // NOI18N
        jButton6.setToolTipText("salir");
        jButton6.setDisabledSelectedIcon(null);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setOpaque(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(560, 10, 30, 33);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/regresar.png"))); // NOI18N
        jButton7.setToolTipText("regresar");
        jButton7.setDisabledSelectedIcon(null);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setOpaque(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(500, 10, 30, 33);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escoba.png"))); // NOI18N
        jButton5.setToolTipText("limpiar");
        jButton5.setDisabledSelectedIcon(null);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(530, 10, 30, 33);

        jLabel3.setBackground(new java.awt.Color(51, 102, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Nombre del empleado:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 220, 210, 20);

        jLabel4.setBackground(new java.awt.Color(51, 102, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Numero de empleado:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 260, 210, 20);

        jLabel5.setBackground(new java.awt.Color(51, 102, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("Puesto:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 300, 70, 20);

        jLabel6.setBackground(new java.awt.Color(51, 102, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("Salario Diario:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 330, 140, 20);

        jLabel7.setBackground(new java.awt.Color(51, 102, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("Dias trabajados:");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 360, 160, 20);

        jLabel8.setBackground(new java.awt.Color(51, 102, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setText("Horas extras:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(140, 390, 130, 20);

        jLabel9.setBackground(new java.awt.Color(51, 102, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 51));
        jLabel9.setText("Faltas:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(200, 420, 60, 20);

        jLabel10.setBackground(new java.awt.Color(51, 102, 0));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 51));
        jLabel10.setText("Salario Neto:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(150, 450, 120, 20);

        jLabel11.setBackground(new java.awt.Color(51, 102, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 51));
        jLabel11.setText("Impuestos retenidos:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 480, 200, 20);

        jLabel12.setBackground(new java.awt.Color(51, 102, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 51));
        jLabel12.setText("Seguro Medico:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(120, 510, 160, 20);

        jLabel13.setBackground(new java.awt.Color(51, 102, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 51));
        jLabel13.setText("Monto Horas Extras:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(80, 540, 190, 20);

        jLabel14.setBackground(new java.awt.Color(51, 102, 0));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 51));
        jLabel14.setText("Bono:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(210, 570, 60, 20);

        jLabel15.setBackground(new java.awt.Color(51, 102, 0));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 51));
        jLabel15.setText("Total a recibir:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(130, 600, 140, 20);

        l1.setBackground(new java.awt.Color(255, 255, 51));
        l1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(l1);
        l1.setBounds(330, 220, 120, 20);

        l2.setBackground(new java.awt.Color(255, 255, 51));
        l2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(l2);
        l2.setBounds(330, 260, 120, 20);

        l3.setBackground(new java.awt.Color(255, 255, 51));
        l3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(l3);
        l3.setBounds(330, 300, 120, 20);

        l4.setBackground(new java.awt.Color(255, 255, 51));
        l4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(l4);
        l4.setBounds(330, 330, 120, 20);

        l5.setBackground(new java.awt.Color(255, 255, 51));
        l5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(l5);
        l5.setBounds(330, 360, 120, 20);

        l6.setBackground(new java.awt.Color(255, 255, 51));
        l6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l6.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(l6);
        l6.setBounds(330, 390, 120, 20);

        l7.setBackground(new java.awt.Color(255, 255, 51));
        l7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l7.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(l7);
        l7.setBounds(330, 420, 120, 20);

        l8.setBackground(new java.awt.Color(255, 255, 51));
        l8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l8.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(l8);
        l8.setBounds(330, 450, 120, 20);

        l9.setBackground(new java.awt.Color(255, 255, 51));
        l9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l9.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(l9);
        l9.setBounds(330, 480, 120, 20);

        l10.setBackground(new java.awt.Color(255, 255, 51));
        l10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l10.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(l10);
        l10.setBounds(330, 510, 120, 20);

        l11.setBackground(new java.awt.Color(255, 255, 51));
        l11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l11.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(l11);
        l11.setBounds(330, 540, 120, 20);

        l12.setBackground(new java.awt.Color(255, 255, 51));
        l12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l12.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(l12);
        l12.setBounds(330, 570, 120, 20);

        l13.setBackground(new java.awt.Color(255, 255, 51));
        l13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l13.setForeground(new java.awt.Color(255, 255, 51));
        l13.setToolTipText("");
        getContentPane().add(l13);
        l13.setBounds(330, 600, 120, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Empresa x");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 90, 340, 90);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 180, 590, 20);

        jLabel16.setBackground(new java.awt.Color(0, 153, 0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 153));
        jLabel16.setText("Recibo");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(200, 30, 220, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p2.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 610, 670);

        jMenuBar2.setBackground(new java.awt.Color(51, 255, 255));

        jMenu3.setBackground(new java.awt.Color(0, 51, 255));
        jMenu3.setText("Opciones");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcular.png"))); // NOI18N
        jMenuItem1.setText("Calcular");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escoba.png"))); // NOI18N
        jMenuItem2.setText("Limpiar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/regresar.png"))); // NOI18N
        jMenuItem3.setText("Regresar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x.png"))); // NOI18N
        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        		//nombre del empleado
                        do
                        {
		nom=JOptionPane.showInputDialog("Ingresa el nombre del empleado");
                if(nom.isEmpty())
                {
                    JOptionPane.showMessageDialog(null,"Tiene que ingresar un numbre","Error",JOptionPane.ERROR_MESSAGE);
                }
                        }
                        while(nom.isEmpty());
                //numero de empleado
                do
                {
                ne=Integer.parseInt(JOptionPane.showInputDialog("Ingresa el numero de empleado"));
                if(ne<=0)
                {
                    JOptionPane.showMessageDialog(null,"Error\nUnicamente puedes ingresar numeros mayores a cero");
                }
                }
                while(ne<=0);
		//puesto del empleado
		p=(String) JOptionPane.showInputDialog(null,"Ingresa el puesto del empleado","Empleado",JOptionPane.QUESTION_MESSAGE,null,pues,pues[0]);
		//dias trabajados
	    	dato=(String) JOptionPane.showInputDialog(null,"Ingresa el numero de dias trabajadas","Dias Trabajados",JOptionPane.QUESTION_MESSAGE,null,dit,dit[0]);
	    	dt=Integer.parseInt(dato);

	    do
	    {
	    	sd=Integer.parseInt(JOptionPane.showInputDialog("Ingresa el salario diario"));
	    	if(sd<=0)
	    	{
	    		JOptionPane.showMessageDialog(null,"Error\nUnicamente puede ingresar numeros mayor a cero");
	    	}
	    }
	    while(sd<=0);
	    do
	    {
	    	het=Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese el numero de horas extras trabajadas"));
	    	if(het<0)
	    	{
	    		JOptionPane.showMessageDialog(null,"Error\nUnicamente puede ingresar numeros de 0 en adelante");
	    	}
	    }
	    while(het<0);
                d=0;
		des=0;
		sn=dt*sd;
		d=(float) (sn*0.0285);
		sm=(float) (sn*0.0328);
		f=15-dt;
		if(het<=9)
		{
			mhe=(het*(sd/8)*2);
		}
		if(het>9)
		{
			mhe=(((sd/8)*(het-9)*3)+(9*(sd/8)*2)+250);
		}
		if(dt==15)
		{
			bono=(float) (sn*0.08);
		}
		if(f>=3)
		{
			des=(sd*40);
		}
		tp=bono+des+mhe+(sn-d-sm);
                nom=nom.toUpperCase();
                p=p.toUpperCase();
                l1.setText(nom.toString());
                l2.setText(Integer.toString(ne));
                l3.setText(p.toString());
                l4.setText(Float.toString(sd));
                l5.setText(Integer.toString(dt));
                l6.setText(Integer.toString(het));
                l7.setText(Integer.toString(f));
                l8.setText(Float.toString(sn));
                l9.setText(Float.toString(d));
                l10.setText(Float.toString(sm));
                l11.setText(Float.toString(mhe));
                l12.setText(Float.toString(bono));
                l13.setText(Float.toString(tp));
                	if(f>=3)
			{
				JOptionPane.showMessageDialog(null,"Despedido");
			}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Escritorio().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por utilizar el sistema");
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        l1.setText("");
        l2.setText("");
        l3.setText("");
        l4.setText("");
        l5.setText("");
        l6.setText("");
        l7.setText("");
        l8.setText("");
        l9.setText("");
        l10.setText("");
        l11.setText("");
        l12.setText("");
        l13.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        l1.setText("");
        l2.setText("");
        l3.setText("");
        l4.setText("");
        l5.setText("");
        l6.setText("");
        l7.setText("");
        l8.setText("");
        l9.setText("");
        l10.setText("");
        l11.setText("");
        l12.setText("");
        l13.setText("");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        	//nombre del empleado
		do
                        {
		nom=JOptionPane.showInputDialog("Ingresa el nombre del empleado");
                if(nom.isEmpty())
                {
                    JOptionPane.showMessageDialog(null,"Tiene que ingresar un nombre","Error",JOptionPane.ERROR_MESSAGE);
                }
                        }
                        while(nom.isEmpty());
                //numero de empleado
                do
                {
                ne=Integer.parseInt(JOptionPane.showInputDialog("Ingresa el numero de empleado"));
                if(ne<=0)
                {
                    JOptionPane.showMessageDialog(null,"Error\nUnicamente puedes ingresar numeros mayores a cero");
                }
                }
                while(ne<=0);
		//puesto del empleado
		p=(String) JOptionPane.showInputDialog(null,"Ingresa el puesto del empleado","Empleado",JOptionPane.QUESTION_MESSAGE,null,pues,pues[0]);
		//dias trabajados
	    	dato=(String) JOptionPane.showInputDialog(null,"Ingresa el numero de dias trabajadas","Dias Trabajados",JOptionPane.QUESTION_MESSAGE,null,dit,dit[0]);
	    	dt=Integer.parseInt(dato);

	    do
	    {
	    	sd=Integer.parseInt(JOptionPane.showInputDialog("Ingresa el salario diario"));
	    	if(sd<=0)
	    	{
	    		JOptionPane.showMessageDialog(null,"Error\nUnicamente puede ingresar numeros mayor a cero");
	    	}
	    }
	    while(sd<=0);
	    do
	    {
	    	het=Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese el numero de horas extras trabajadas"));
	    	if(het<0)
	    	{
	    		JOptionPane.showMessageDialog(null,"Error\nUnicamente puede ingresar numeros de 0 en adelante");
	    	}
	    }
	    while(het<0);
                d=0;
		des=0;
		sn=dt*sd;
		d=(float) (sn*0.0285);
		sm=(float) (sn*0.0328);
		f=15-dt;
		if(het<=9)
		{
			mhe=(het*(sd/8)*2);
		}
		if(het>9)
		{
			mhe=(((sd/8)*(het-9)*3)+(9*(sd/8)*2)+250);
		}
		if(dt==15)
		{
			bono=(float) (sn*0.08);
		}
		if(f>=3)
		{
			des=(sd*40);
		}
		tp=bono+des+mhe+(sn-d-sm);
                nom=nom.toUpperCase();
                p=p.toUpperCase();
                l1.setText(nom.toString());
                l2.setText(Integer.toString(ne));
                l3.setText(p.toString());
                l4.setText(q.format(sd));
                l5.setText(Integer.toString(dt));
                l6.setText(Integer.toString(het));
                l7.setText(Integer.toString(f));
                l8.setText(q.format(sn));
                l9.setText(q.format(d));
                l10.setText(q.format(sm));
                l11.setText(q.format(mhe));
                l12.setText(q.format(bono));
                l13.setText(q.format(tp));
                	if(f>=3)
			{
				JOptionPane.showMessageDialog(null,"Despedido");
			}
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Escritorio().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Gracias por utilizar el sistema");
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReciboDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReciboDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReciboDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReciboDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReciboDePago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables
}
