
import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author leonardo
 */
public class Selección extends javax.swing.JFrame {
String nom;
int bol, ojp1, ojp2, ojp3, d1, d2, d3, poo1, poo2, poo3, co1, co2, co3, ci1, ci2, ci3, i1, i2, i3, bd1, bd2, bd3, m1, m2, m3, iuc1, iuc2, iuc3;
float prom1, prom2, prom3, prom4, prom5, prom6, prom7, prom8, prom9, pp, ps, pt, pg; 
DecimalFormat r=new DecimalFormat("#.##");
    /**
     * Creates new form Selección
     */
    public Selección() {
        
        initComponents();
        this.setSize(1070,690);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        c2 = new javax.swing.JComboBox<>();
        c3 = new javax.swing.JComboBox<>();
        c4 = new javax.swing.JComboBox<>();
        c5 = new javax.swing.JComboBox<>();
        c6 = new javax.swing.JComboBox<>();
        c7 = new javax.swing.JComboBox<>();
        c8 = new javax.swing.JComboBox<>();
        c9 = new javax.swing.JComboBox<>();
        c10 = new javax.swing.JComboBox<>();
        c11 = new javax.swing.JComboBox<>();
        c12 = new javax.swing.JComboBox<>();
        c13 = new javax.swing.JComboBox<>();
        c14 = new javax.swing.JComboBox<>();
        c15 = new javax.swing.JComboBox<>();
        c16 = new javax.swing.JComboBox<>();
        c17 = new javax.swing.JComboBox<>();
        c18 = new javax.swing.JComboBox<>();
        c19 = new javax.swing.JComboBox<>();
        c20 = new javax.swing.JComboBox<>();
        c21 = new javax.swing.JComboBox<>();
        c22 = new javax.swing.JComboBox<>();
        c23 = new javax.swing.JComboBox<>();
        c24 = new javax.swing.JComboBox<>();
        c25 = new javax.swing.JComboBox<>();
        c26 = new javax.swing.JComboBox<>();
        c27 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Nombre del alumno:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 130, 260, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("5° Semestre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 230, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Informatica");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(890, 0, 180, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boleta+.png"))); // NOI18N
        jLabel4.setText("Boleta");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 10, 390, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Numero de boleta:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(590, 120, 250, 20);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(280, 130, 181, 30);

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(820, 120, 181, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Materia");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 190, 330, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Orientacion Juvenil  y Profesional III");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 220, 460, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Derecho II");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 270, 340, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Programacion Orientada a Objetos");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 300, 460, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Contabilidad III");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 350, 350, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Calculo Integral");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 380, 360, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Ingles V");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 420, 320, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Base de datos");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 470, 360, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Microeconomía");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 500, 360, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Interaccion usuario computadora");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 540, 450, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Calificación 1");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(500, 180, 190, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Calificacion 2");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(700, 180, 180, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Calificacion 3");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(890, 180, 190, 20);

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(550, 230, 56, 20);

        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2);
        c2.setBounds(770, 230, 56, 20);

        c3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        getContentPane().add(c3);
        c3.setBounds(950, 230, 56, 20);

        c4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        getContentPane().add(c4);
        c4.setBounds(550, 270, 56, 20);

        c5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });
        getContentPane().add(c5);
        c5.setBounds(770, 270, 56, 20);

        c6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });
        getContentPane().add(c6);
        c6.setBounds(950, 270, 56, 20);

        c7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c7ActionPerformed(evt);
            }
        });
        getContentPane().add(c7);
        c7.setBounds(550, 320, 56, 20);

        c8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c8ActionPerformed(evt);
            }
        });
        getContentPane().add(c8);
        c8.setBounds(770, 320, 56, 20);

        c9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c9ActionPerformed(evt);
            }
        });
        getContentPane().add(c9);
        c9.setBounds(950, 320, 56, 20);

        c10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c10ActionPerformed(evt);
            }
        });
        getContentPane().add(c10);
        c10.setBounds(550, 350, 56, 20);

        c11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c11ActionPerformed(evt);
            }
        });
        getContentPane().add(c11);
        c11.setBounds(770, 350, 56, 20);

        c12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c12ActionPerformed(evt);
            }
        });
        getContentPane().add(c12);
        c12.setBounds(950, 350, 56, 20);

        c13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c13ActionPerformed(evt);
            }
        });
        getContentPane().add(c13);
        c13.setBounds(550, 400, 56, 20);

        c14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c14ActionPerformed(evt);
            }
        });
        getContentPane().add(c14);
        c14.setBounds(770, 400, 56, 20);

        c15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c15ActionPerformed(evt);
            }
        });
        getContentPane().add(c15);
        c15.setBounds(950, 400, 56, 20);

        c16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c16ActionPerformed(evt);
            }
        });
        getContentPane().add(c16);
        c16.setBounds(550, 440, 56, 20);

        c17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c17ActionPerformed(evt);
            }
        });
        getContentPane().add(c17);
        c17.setBounds(770, 440, 56, 20);

        c18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c18ActionPerformed(evt);
            }
        });
        getContentPane().add(c18);
        c18.setBounds(950, 440, 56, 20);

        c19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c19ActionPerformed(evt);
            }
        });
        getContentPane().add(c19);
        c19.setBounds(550, 470, 56, 20);

        c20.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c20ActionPerformed(evt);
            }
        });
        getContentPane().add(c20);
        c20.setBounds(770, 470, 56, 20);

        c21.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c21ActionPerformed(evt);
            }
        });
        getContentPane().add(c21);
        c21.setBounds(950, 470, 56, 20);

        c22.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c22ActionPerformed(evt);
            }
        });
        getContentPane().add(c22);
        c22.setBounds(550, 500, 56, 20);

        c23.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c23ActionPerformed(evt);
            }
        });
        getContentPane().add(c23);
        c23.setBounds(770, 500, 56, 20);

        c24.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c24ActionPerformed(evt);
            }
        });
        getContentPane().add(c24);
        c24.setBounds(950, 500, 56, 20);

        c25.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c25ActionPerformed(evt);
            }
        });
        getContentPane().add(c25);
        c25.setBounds(550, 550, 56, 20);

        c26.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c26ActionPerformed(evt);
            }
        });
        getContentPane().add(c26);
        c26.setBounds(770, 550, 56, 20);

        c27.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        c27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c27ActionPerformed(evt);
            }
        });
        getContentPane().add(c27);
        c27.setBounds(950, 550, 56, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/generar.png"))); // NOI18N
        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 600, 120, 33);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escoba.png"))); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 600, 110, 33);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/regresar.png"))); // NOI18N
        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(320, 600, 110, 33);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x.png"))); // NOI18N
        jButton4.setText("Cerrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(440, 600, 100, 33);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boles.png"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(300, 0, 100, 100);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(-20, 590, 1070, 60);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calificacion.jpg"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(0, 0, 1070, 640);

        jMenu1.setText("Opciones");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/generar.png"))); // NOI18N
        jMenuItem1.setText("Generar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escoba.png"))); // NOI18N
        jMenuItem2.setText("limpiar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/regresar.png"))); // NOI18N
        jMenuItem3.setText("regresar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x.png"))); // NOI18N
        jMenuItem4.setText("cerrar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if(t1.getText().isEmpty()||t2.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Datos Vacios");
        }
        else
        {
            //declaracion del .java
            Semestre S=new Semestre();
            //conversion de los datos ingresados en los text field
             nom=t1.getText();
             bol=Integer.parseInt(t2.getText());
             //cambio a mayusculas del  nombre
             nom=nom.toUpperCase();
             //calculo de los promedios individuales por materia
             prom1=(ojp1+ojp2+ojp3)/3;
             prom2=(d1+d2+d3)/3;
             prom3=(poo1+poo2+poo3)/3;
             prom4=(co1+co2+co3)/3;
             prom5=(ci1+ci2+ci3)/3;
             prom6=(i1+i2+i3)/3;
             prom7=(bd1+bd2+bd3)/3;
             prom8=(m1+m2+m3)/3;
             prom9=(iuc1+iuc2+iuc3)/3;
             //Promedios generales
             pp=(ojp1+d1+poo1+co1+ci1+i1+bd1+m1+iuc1)/9;
             ps=(ojp2+d2+poo2+co2+ci2+i2+bd2+m2+iuc2)/9;
             pt=(ojp3+d3+poo3+co3+ci3+i3+bd3+m3+iuc3)/9;
             pg=(prom1+prom2+prom3+prom4+prom5+prom6+prom7+prom8+prom9)/9;
             //Condicional de los promedios
             if(pp>=6)
             {
                 S.l39.setForeground(Color.green);
             }
             else
             {
                 S.l39.setForeground(Color.red);
             }
             if(ps>=6)
             {
                 S.l40.setForeground(Color.green);
             }
             else
             {
                 S.l40.setForeground(Color.red);
             }
             if(pt>=6)
             {
                 S.l41.setForeground(Color.green);
             }
             else
             {
                 S.l41.setForeground(Color.red);
             }
             if(pg>=6)
             {
                 S.l42.setForeground(Color.green);
             }
             else
             {
                 S.l42.setForeground(Color.red);
             }
             
             
             //condicionales del color de la materia de orientacion
             if(ojp1>=6)
             {
                 S.l3.setForeground(Color.green);
             }
             else
             {
                 S.l3.setForeground(Color.red);
             }
             if(ojp2>=6)
             {
                 S.l4.setForeground(Color.green);
             }
             else
             {
                 S.l4.setForeground(Color.red);
             }
             if(ojp3>=6)
             {
                 S.l5.setForeground(Color.green);
             }
             else
             {
                 S.l5.setForeground(Color.red);
             }
             if(prom1>=6)
             {
                 S.l6.setForeground(Color.green);
             }
             else
             {
                 S.l6.setForeground(Color.red);
             }
             //condicionales de la materia de derecho
             if(d1>=6)
             {
                 S.l7.setForeground(Color.green);
             }
             else
             {
                 S.l7.setForeground(Color.red);
             }
             if(d2>=6)
             {
                 S.l8.setForeground(Color.green);
             }
             else
             {
                 S.l8.setForeground(Color.red);
             }
             if(d3>=6)
             {
                 S.l9.setForeground(Color.green);
             }
             else
             {
                 S.l9.setForeground(Color.red);
             }
             if(prom2>=6)
             {
                 S.l10.setForeground(Color.green);
             }
             else
             {
                 S.l10.setForeground(Color.red);
             }
             //condicional de programacion
             if(poo1>=6)
             {
                 S.l11.setForeground(Color.green);
             }
             else
             {
                 S.l11.setForeground(Color.red);
             }
             if(poo2>=6)
             {
                 S.l12.setForeground(Color.green);
             }
             else
             {
                 S.l12.setForeground(Color.red);
             }
             if(poo3>=6)
             {
                 S.l13.setForeground(Color.green);
             }
             else
             {
                 S.l13.setForeground(Color.red);
             }
             if(prom3>=6)
             {
                 S.l14.setForeground(Color.green);
             }
             else
             {
                 S.l14.setForeground(Color.red);
             }
             //condicional de contabilidad
             if(co1>=6)
             {
                 S.l15.setForeground(Color.green);
             }
             else
             {
                 S.l15.setForeground(Color.red);
             }
             if(co2>=6)
             {
                 S.l16.setForeground(Color.green);
             }
             else
             {
                 S.l16.setForeground(Color.red);
             }
             if(co3>=6)
             {
                 S.l17.setForeground(Color.green);
             }
             else
             {
                 S.l17.setForeground(Color.red);
             }
             if(prom4>=6)
             {
                 S.l18.setForeground(Color.green);
             }
             else
             {
                 S.l18.setForeground(Color.red);
             }
             //Condicional CAlculo integral
             if(ci1>=6)
             {
                 S.l19.setForeground(Color.green);
             }
             else
             {
                 S.l19.setForeground(Color.red);
             }
             if(ci2>=6)
             {
                 S.l20.setForeground(Color.green);
             }
             else
             {
                 S.l20.setForeground(Color.red);
             }
             if(ci3>=6)
             {
                 S.l21.setForeground(Color.green);
             }
             else
             {
                 S.l21.setForeground(Color.red);
             }
             if(prom5>=6)
             {
                 S.l22.setForeground(Color.green);
             }
             else
             {
                 S.l22.setForeground(Color.red);
             }
             //condicional de ingles
             if(i1>=6)
             {
                 S.l23.setForeground(Color.green);
             }
             else
             {
                 S.l23.setForeground(Color.red);
             }
             if(i2>=6)
             {
                 S.l24.setForeground(Color.green);
             }
             else
             {
                 S.l24.setForeground(Color.red);
             }
             if(i3>=6)
             {
                 S.l25.setForeground(Color.green);
             }
             else
             {
                 S.l25.setForeground(Color.red);
             }
             if(prom6>=6)
             {
                 S.l26.setForeground(Color.green);
             }
             else
             {
                 S.l26.setForeground(Color.red);
             }
             //Condicional de base de datos
             if(bd1>=6)
             {
                 S.l27.setForeground(Color.green);
             }
             else
             {
                 S.l27.setForeground(Color.red);
             }
             if(bd2>=6)
             {
                 S.l28.setForeground(Color.green);
             }
             else
             {
                 S.l28.setForeground(Color.red);
             }
             if(bd3>=6)
             {
                 S.l29.setForeground(Color.green);
             }
             else
             {
                 S.l29.setForeground(Color.red);
             }
             if(prom7>=6)
             {
                 S.l30.setForeground(Color.green);
             }
             else
             {
                 S.l30.setForeground(Color.red);
             }
             //Condicional de microeconomia
             if(m1>=6)
             {
                 S.l31.setForeground(Color.green);
             }
             else
             {
                 S.l31.setForeground(Color.red);
             }
             if(m2>=6)
             {
                 S.l32.setForeground(Color.green);
             }
             else
             {
                 S.l32.setForeground(Color.red);
             }
             if(m3>=6)
             {
                 S.l33.setForeground(Color.green);
             }
             else
             {
                 S.l33.setForeground(Color.red);
             }
             if(prom8>=6)
             {
                 S.l34.setForeground(Color.green);
             }
             else
             {
                 S.l34.setForeground(Color.red);
             }
             //Condicional de interaccion
             if(iuc1>=6)
             {
                 S.l35.setForeground(Color.green);
             }
             else
             {
                 S.l35.setForeground(Color.red);
             }
             if(iuc2>=6)
             {
                 S.l36.setForeground(Color.green);
             }
             else
             {
                 S.l36.setForeground(Color.red);
             }
             if(iuc3>=6)
             {
                 S.l37.setForeground(Color.green);
             }
             else
             {
                 S.l37.setForeground(Color.red);
             }
             if(prom9>=6)
             {
                 S.l38.setForeground(Color.green);
             }
             else
             {
                 S.l38.setForeground(Color.red);
             }
             //tipo de letra y tamaño de las calificaciones de boleta genearada
             S.l1.setFont(new java.awt.Font("Algerian", 1, 24));
             S.l2.setFont(new java.awt.Font("Algerian", 1, 24));
             S.l3.setFont(new java.awt.Font("Arial", 1, 24));
             S.l4.setFont(new java.awt.Font("Arial", 1, 24));
             S.l5.setFont(new java.awt.Font("Arial", 1, 24));
             S.l6.setFont(new java.awt.Font("Arial", 1, 24));
             S.l7.setFont(new java.awt.Font("Arial", 1, 24));
             S.l8.setFont(new java.awt.Font("Arial", 1, 24));
             S.l9.setFont(new java.awt.Font("Arial", 1, 24));
             S.l10.setFont(new java.awt.Font("Arial", 1, 24));
             S.l11.setFont(new java.awt.Font("Arial", 1, 24));
             S.l12.setFont(new java.awt.Font("Arial", 1, 24));
             S.l13.setFont(new java.awt.Font("Arial", 1, 24));
             S.l14.setFont(new java.awt.Font("Arial", 1, 24));
             S.l15.setFont(new java.awt.Font("Arial", 1, 24));
             S.l16.setFont(new java.awt.Font("Arial", 1, 24));
             S.l17.setFont(new java.awt.Font("Arial", 1, 24));
             S.l18.setFont(new java.awt.Font("Arial", 1, 24));
             S.l19.setFont(new java.awt.Font("Arial", 1, 24));
             S.l20.setFont(new java.awt.Font("Arial", 1, 24));
             S.l21.setFont(new java.awt.Font("Arial", 1, 24));
             S.l22.setFont(new java.awt.Font("Arial", 1, 24));
             S.l23.setFont(new java.awt.Font("Arial", 1, 24));
             S.l24.setFont(new java.awt.Font("Arial", 1, 24));
             S.l25.setFont(new java.awt.Font("Arial", 1, 24));
             S.l26.setFont(new java.awt.Font("Arial", 1, 24));
             S.l27.setFont(new java.awt.Font("Arial", 1, 24));
             S.l28.setFont(new java.awt.Font("Arial", 1, 24));
             S.l29.setFont(new java.awt.Font("Arial", 1, 24));
             S.l30.setFont(new java.awt.Font("Arial", 1, 24));
             S.l31.setFont(new java.awt.Font("Arial", 1, 24));
             S.l32.setFont(new java.awt.Font("Arial", 1, 24));
             S.l33.setFont(new java.awt.Font("Arial", 1, 24));
             S.l34.setFont(new java.awt.Font("Arial", 1, 24));
             S.l35.setFont(new java.awt.Font("Arial", 1, 24));
             S.l36.setFont(new java.awt.Font("Arial", 1, 24));
             S.l37.setFont(new java.awt.Font("Arial", 1, 24));
             S.l38.setFont(new java.awt.Font("Arial", 1, 24));
             //mostrar los datos
             S.setVisible(true);
             S.l1.setText(nom.toString());
             S.l2.setText(Integer.toString(bol));
             S.l3.setText(Integer.toString(ojp1));
             S.l4.setText(Integer.toString(ojp2));
             S.l5.setText(Integer.toString(ojp3));
             S.l6.setText(r.format(prom1));
             S.l7.setText(Integer.toString(d1));
             S.l8.setText(Integer.toString(d2));
             S.l9.setText(Integer.toString(d3));
             S.l10.setText(r.format(prom2));
             S.l11.setText(Integer.toString(poo1));
             S.l12.setText(Integer.toString(poo2));
             S.l13.setText(Integer.toString(poo3));
             S.l14.setText(r.format(prom3));
             S.l15.setText(Integer.toString(co1));
             S.l16.setText(Integer.toString(co2));
             S.l17.setText(Integer.toString(co3));
             S.l18.setText(r.format(prom4));
             S.l19.setText(Integer.toString(ci1));
             S.l20.setText(Integer.toString(ci2));
             S.l21.setText(Integer.toString(ci3));
             S.l22.setText(r.format(prom5));
             S.l23.setText(Integer.toString(i1));
             S.l24.setText(Integer.toString(i2));
             S.l25.setText(Integer.toString(i3));
             S.l26.setText(r.format(prom6));
             S.l27.setText(Integer.toString(bd1));
             S.l28.setText(Integer.toString(bd2));
             S.l29.setText(Integer.toString(bd3));
             S.l30.setText(r.format(prom7));
             S.l31.setText(Integer.toString(m1));
             S.l32.setText(Integer.toString(m2));
             S.l33.setText(Integer.toString(m3));
             S.l34.setText(r.format(prom8));
             S.l35.setText(Integer.toString(iuc1));
             S.l36.setText(Integer.toString(iuc2));
             S.l37.setText(Integer.toString(iuc3));
             S.l38.setText(r.format(prom9));
             //mostrar los promedios
             S.l39.setFont(new java.awt.Font("Arial", 1, 24));
             S.l40.setFont(new java.awt.Font("Arial", 1, 24));
             S.l41.setFont(new java.awt.Font("Arial", 1, 24));
             S.l42.setFont(new java.awt.Font("Arial", 1, 24));
             S.l39.setText(Float.toString(pp));
             S.l40.setText(Float.toString(ps));
             S.l41.setText(Float.toString(pt));
             S.l42.setText(Float.toString(pg));
             this.dispose();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
        ojp1=Integer.parseInt(c1.getSelectedItem().toString());
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
        ojp2=Integer.parseInt(c2.getSelectedItem().toString());
    }//GEN-LAST:event_c2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
        ojp3=Integer.parseInt(c3.getSelectedItem().toString());
    }//GEN-LAST:event_c3ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
        d1=Integer.parseInt(c4.getSelectedItem().toString());
    }//GEN-LAST:event_c4ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        // TODO add your handling code here:
        d2=Integer.parseInt(c5.getSelectedItem().toString());
    }//GEN-LAST:event_c5ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        // TODO add your handling code here:
        d3=Integer.parseInt(c6.getSelectedItem().toString());
    }//GEN-LAST:event_c6ActionPerformed

    private void c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c7ActionPerformed
        // TODO add your handling code here:
        poo1=Integer.parseInt(c7.getSelectedItem().toString());
    }//GEN-LAST:event_c7ActionPerformed

    private void c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c8ActionPerformed
        // TODO add your handling code here:
        poo2=Integer.parseInt(c8.getSelectedItem().toString());
    }//GEN-LAST:event_c8ActionPerformed

    private void c9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c9ActionPerformed
        // TODO add your handling code here:
        poo3=Integer.parseInt(c9.getSelectedItem().toString());
    }//GEN-LAST:event_c9ActionPerformed

    private void c10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c10ActionPerformed
        // TODO add your handling code here:
        co1=Integer.parseInt(c10.getSelectedItem().toString());
    }//GEN-LAST:event_c10ActionPerformed

    private void c11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c11ActionPerformed
        // TODO add your handling code here:
        co2=Integer.parseInt(c11.getSelectedItem().toString());
    }//GEN-LAST:event_c11ActionPerformed

    private void c12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c12ActionPerformed
        // TODO add your handling code here:
        co3=Integer.parseInt(c12.getSelectedItem().toString());
    }//GEN-LAST:event_c12ActionPerformed

    private void c13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c13ActionPerformed
        // TODO add your handling code here:
        ci1=Integer.parseInt(c13.getSelectedItem().toString());
    }//GEN-LAST:event_c13ActionPerformed

    private void c14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c14ActionPerformed
        // TODO add your handling code here:
        ci2=Integer.parseInt(c14.getSelectedItem().toString());
    }//GEN-LAST:event_c14ActionPerformed

    private void c15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c15ActionPerformed
        // TODO add your handling code here:
        ci3=Integer.parseInt(c15.getSelectedItem().toString());
    }//GEN-LAST:event_c15ActionPerformed

    private void c16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c16ActionPerformed
        // TODO add your handling code here:
        i1=Integer.parseInt(c16.getSelectedItem().toString());
    }//GEN-LAST:event_c16ActionPerformed

    private void c17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c17ActionPerformed
        // TODO add your handling code here:
        i2=Integer.parseInt(c17.getSelectedItem().toString());
    }//GEN-LAST:event_c17ActionPerformed

    private void c18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c18ActionPerformed
        // TODO add your handling code here:
        i3=Integer.parseInt(c18.getSelectedItem().toString());
    }//GEN-LAST:event_c18ActionPerformed

    private void c19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c19ActionPerformed
        // TODO add your handling code here:
        bd1=Integer.parseInt(c19.getSelectedItem().toString());
    }//GEN-LAST:event_c19ActionPerformed

    private void c20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c20ActionPerformed
        // TODO add your handling code here:
        bd2=Integer.parseInt(c20.getSelectedItem().toString());
    }//GEN-LAST:event_c20ActionPerformed

    private void c21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c21ActionPerformed
        // TODO add your handling code here:
        bd3=Integer.parseInt(c21.getSelectedItem().toString());
    }//GEN-LAST:event_c21ActionPerformed

    private void c22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c22ActionPerformed
        // TODO add your handling code here:
        m1=Integer.parseInt(c22.getSelectedItem().toString());
    }//GEN-LAST:event_c22ActionPerformed

    private void c23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c23ActionPerformed
        // TODO add your handling code here:
        m2=Integer.parseInt(c23.getSelectedItem().toString());
    }//GEN-LAST:event_c23ActionPerformed

    private void c24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c24ActionPerformed
        // TODO add your handling code here:
        m3=Integer.parseInt(c24.getSelectedItem().toString());
    }//GEN-LAST:event_c24ActionPerformed

    private void c25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c25ActionPerformed
        // TODO add your handling code here:
        iuc1=Integer.parseInt(c25.getSelectedItem().toString());
    }//GEN-LAST:event_c25ActionPerformed

    private void c26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c26ActionPerformed
        // TODO add your handling code here:
        iuc2=Integer.parseInt(c26.getSelectedItem().toString());
    }//GEN-LAST:event_c26ActionPerformed

    private void c27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c27ActionPerformed
        // TODO add your handling code here:
        iuc3=Integer.parseInt(c27.getSelectedItem().toString());
    }//GEN-LAST:event_c27ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(t1.getText().isEmpty()||t2.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Datos Vacios");
        }
        else
        {
            //declaracion del .java
            Semestre S=new Semestre();
            //conversion de los datos ingresados en los text field
             nom=t1.getText();
             bol=Integer.parseInt(t2.getText());
             //cambio a mayusculas del  nombre
             nom=nom.toUpperCase();
             //calculo de los promedios individuales por materia
             prom1=(ojp1+ojp2+ojp3)/3;
             prom2=(d1+d2+d3)/3;
             prom3=(poo1+poo2+poo3)/3;
             prom4=(co1+co2+co3)/3;
             prom5=(ci1+ci2+ci3)/3;
             prom6=(i1+i2+i3)/3;
             prom7=(bd1+bd2+bd3)/3;
             prom8=(m1+m2+m3)/3;
             prom9=(iuc1+iuc2+iuc3)/3;
             //Promedios generales
             pp=(ojp1+d1+poo1+co1+ci1+i1+bd1+m1+iuc1)/9;
             ps=(ojp2+d2+poo2+co2+ci2+i2+bd2+m2+iuc2)/9;
             pt=(ojp3+d3+poo3+co3+ci3+i3+bd3+m3+iuc3)/9;
             pg=(prom1+prom2+prom3+prom4+prom5+prom6+prom7+prom8+prom9)/9;
             //Condicional de los promedios
             if(pp>=6)
             {
                 S.l39.setForeground(Color.green);
             }
             else
             {
                 S.l39.setForeground(Color.red);
             }
             if(ps>=6)
             {
                 S.l40.setForeground(Color.green);
             }
             else
             {
                 S.l40.setForeground(Color.red);
             }
             if(pt>=6)
             {
                 S.l41.setForeground(Color.green);
             }
             else
             {
                 S.l41.setForeground(Color.red);
             }
             if(pg>=6)
             {
                 S.l42.setForeground(Color.green);
             }
             else
             {
                 S.l42.setForeground(Color.red);
             }
             
             
             //condicionales del color de la materia de orientacion
             if(ojp1>=6)
             {
                 S.l3.setForeground(Color.green);
             }
             else
             {
                 S.l3.setForeground(Color.red);
             }
             if(ojp2>=6)
             {
                 S.l4.setForeground(Color.green);
             }
             else
             {
                 S.l4.setForeground(Color.red);
             }
             if(ojp3>=6)
             {
                 S.l5.setForeground(Color.green);
             }
             else
             {
                 S.l5.setForeground(Color.red);
             }
             if(prom1>=6)
             {
                 S.l6.setForeground(Color.green);
             }
             else
             {
                 S.l6.setForeground(Color.red);
             }
             //condicionales de la materia de derecho
             if(d1>=6)
             {
                 S.l7.setForeground(Color.green);
             }
             else
             {
                 S.l7.setForeground(Color.red);
             }
             if(d2>=6)
             {
                 S.l8.setForeground(Color.green);
             }
             else
             {
                 S.l8.setForeground(Color.red);
             }
             if(d3>=6)
             {
                 S.l9.setForeground(Color.green);
             }
             else
             {
                 S.l9.setForeground(Color.red);
             }
             if(prom2>=6)
             {
                 S.l10.setForeground(Color.green);
             }
             else
             {
                 S.l10.setForeground(Color.red);
             }
             //condicional de programacion
             if(poo1>=6)
             {
                 S.l11.setForeground(Color.green);
             }
             else
             {
                 S.l11.setForeground(Color.red);
             }
             if(poo2>=6)
             {
                 S.l12.setForeground(Color.green);
             }
             else
             {
                 S.l12.setForeground(Color.red);
             }
             if(poo3>=6)
             {
                 S.l13.setForeground(Color.green);
             }
             else
             {
                 S.l13.setForeground(Color.red);
             }
             if(prom3>=6)
             {
                 S.l14.setForeground(Color.green);
             }
             else
             {
                 S.l14.setForeground(Color.red);
             }
             //condicional de contabilidad
             if(co1>=6)
             {
                 S.l15.setForeground(Color.green);
             }
             else
             {
                 S.l15.setForeground(Color.red);
             }
             if(co2>=6)
             {
                 S.l16.setForeground(Color.green);
             }
             else
             {
                 S.l16.setForeground(Color.red);
             }
             if(co3>=6)
             {
                 S.l17.setForeground(Color.green);
             }
             else
             {
                 S.l17.setForeground(Color.red);
             }
             if(prom4>=6)
             {
                 S.l18.setForeground(Color.green);
             }
             else
             {
                 S.l18.setForeground(Color.red);
             }
             //Condicional CAlculo integral
             if(ci1>=6)
             {
                 S.l19.setForeground(Color.green);
             }
             else
             {
                 S.l19.setForeground(Color.red);
             }
             if(ci2>=6)
             {
                 S.l20.setForeground(Color.green);
             }
             else
             {
                 S.l20.setForeground(Color.red);
             }
             if(ci3>=6)
             {
                 S.l21.setForeground(Color.green);
             }
             else
             {
                 S.l21.setForeground(Color.red);
             }
             if(prom5>=6)
             {
                 S.l22.setForeground(Color.green);
             }
             else
             {
                 S.l22.setForeground(Color.red);
             }
             //condicional de ingles
             if(i1>=6)
             {
                 S.l23.setForeground(Color.green);
             }
             else
             {
                 S.l23.setForeground(Color.red);
             }
             if(i2>=6)
             {
                 S.l24.setForeground(Color.green);
             }
             else
             {
                 S.l24.setForeground(Color.red);
             }
             if(i3>=6)
             {
                 S.l25.setForeground(Color.green);
             }
             else
             {
                 S.l25.setForeground(Color.red);
             }
             if(prom6>=6)
             {
                 S.l26.setForeground(Color.green);
             }
             else
             {
                 S.l26.setForeground(Color.red);
             }
             //Condicional de base de datos
             if(bd1>=6)
             {
                 S.l27.setForeground(Color.green);
             }
             else
             {
                 S.l27.setForeground(Color.red);
             }
             if(bd2>=6)
             {
                 S.l28.setForeground(Color.green);
             }
             else
             {
                 S.l28.setForeground(Color.red);
             }
             if(bd3>=6)
             {
                 S.l29.setForeground(Color.green);
             }
             else
             {
                 S.l29.setForeground(Color.red);
             }
             if(prom7>=6)
             {
                 S.l30.setForeground(Color.green);
             }
             else
             {
                 S.l30.setForeground(Color.red);
             }
             //Condicional de microeconomia
             if(m1>=6)
             {
                 S.l31.setForeground(Color.green);
             }
             else
             {
                 S.l31.setForeground(Color.red);
             }
             if(m2>=6)
             {
                 S.l32.setForeground(Color.green);
             }
             else
             {
                 S.l32.setForeground(Color.red);
             }
             if(m3>=6)
             {
                 S.l33.setForeground(Color.green);
             }
             else
             {
                 S.l33.setForeground(Color.red);
             }
             if(prom8>=6)
             {
                 S.l34.setForeground(Color.green);
             }
             else
             {
                 S.l34.setForeground(Color.red);
             }
             //Condicional de interaccion
             if(iuc1>=6)
             {
                 S.l35.setForeground(Color.green);
             }
             else
             {
                 S.l35.setForeground(Color.red);
             }
             if(iuc2>=6)
             {
                 S.l36.setForeground(Color.green);
             }
             else
             {
                 S.l36.setForeground(Color.red);
             }
             if(iuc3>=6)
             {
                 S.l37.setForeground(Color.green);
             }
             else
             {
                 S.l37.setForeground(Color.red);
             }
             if(prom9>=6)
             {
                 S.l38.setForeground(Color.green);
             }
             else
             {
                 S.l38.setForeground(Color.red);
             }
             //tipo de letra y tamaño de las calificaciones de boleta genearada
             S.l1.setFont(new java.awt.Font("Algerian", 1, 24));
             S.l2.setFont(new java.awt.Font("Algerian", 1, 24));
             S.l3.setFont(new java.awt.Font("Arial", 1, 24));
             S.l4.setFont(new java.awt.Font("Arial", 1, 24));
             S.l5.setFont(new java.awt.Font("Arial", 1, 24));
             S.l6.setFont(new java.awt.Font("Arial", 1, 24));
             S.l7.setFont(new java.awt.Font("Arial", 1, 24));
             S.l8.setFont(new java.awt.Font("Arial", 1, 24));
             S.l9.setFont(new java.awt.Font("Arial", 1, 24));
             S.l10.setFont(new java.awt.Font("Arial", 1, 24));
             S.l11.setFont(new java.awt.Font("Arial", 1, 24));
             S.l12.setFont(new java.awt.Font("Arial", 1, 24));
             S.l13.setFont(new java.awt.Font("Arial", 1, 24));
             S.l14.setFont(new java.awt.Font("Arial", 1, 24));
             S.l15.setFont(new java.awt.Font("Arial", 1, 24));
             S.l16.setFont(new java.awt.Font("Arial", 1, 24));
             S.l17.setFont(new java.awt.Font("Arial", 1, 24));
             S.l18.setFont(new java.awt.Font("Arial", 1, 24));
             S.l19.setFont(new java.awt.Font("Arial", 1, 24));
             S.l20.setFont(new java.awt.Font("Arial", 1, 24));
             S.l21.setFont(new java.awt.Font("Arial", 1, 24));
             S.l22.setFont(new java.awt.Font("Arial", 1, 24));
             S.l23.setFont(new java.awt.Font("Arial", 1, 24));
             S.l24.setFont(new java.awt.Font("Arial", 1, 24));
             S.l25.setFont(new java.awt.Font("Arial", 1, 24));
             S.l26.setFont(new java.awt.Font("Arial", 1, 24));
             S.l27.setFont(new java.awt.Font("Arial", 1, 24));
             S.l28.setFont(new java.awt.Font("Arial", 1, 24));
             S.l29.setFont(new java.awt.Font("Arial", 1, 24));
             S.l30.setFont(new java.awt.Font("Arial", 1, 24));
             S.l31.setFont(new java.awt.Font("Arial", 1, 24));
             S.l32.setFont(new java.awt.Font("Arial", 1, 24));
             S.l33.setFont(new java.awt.Font("Arial", 1, 24));
             S.l34.setFont(new java.awt.Font("Arial", 1, 24));
             S.l35.setFont(new java.awt.Font("Arial", 1, 24));
             S.l36.setFont(new java.awt.Font("Arial", 1, 24));
             S.l37.setFont(new java.awt.Font("Arial", 1, 24));
             S.l38.setFont(new java.awt.Font("Arial", 1, 24));
             //mostrar los datos
             S.setVisible(true);
             S.l1.setText(nom.toString());
             S.l2.setText(Integer.toString(bol));
             S.l3.setText(Integer.toString(ojp1));
             S.l4.setText(Integer.toString(ojp2));
             S.l5.setText(Integer.toString(ojp3));
             S.l6.setText(r.format(prom1));
             S.l7.setText(Integer.toString(d1));
             S.l8.setText(Integer.toString(d2));
             S.l9.setText(Integer.toString(d3));
             S.l10.setText(r.format(prom2));
             S.l11.setText(Integer.toString(poo1));
             S.l12.setText(Integer.toString(poo2));
             S.l13.setText(Integer.toString(poo3));
             S.l14.setText(r.format(prom3));
             S.l15.setText(Integer.toString(co1));
             S.l16.setText(Integer.toString(co2));
             S.l17.setText(Integer.toString(co3));
             S.l18.setText(r.format(prom4));
             S.l19.setText(Integer.toString(ci1));
             S.l20.setText(Integer.toString(ci2));
             S.l21.setText(Integer.toString(ci3));
             S.l22.setText(r.format(prom5));
             S.l23.setText(Integer.toString(i1));
             S.l24.setText(Integer.toString(i2));
             S.l25.setText(Integer.toString(i3));
             S.l26.setText(r.format(prom6));
             S.l27.setText(Integer.toString(bd1));
             S.l28.setText(Integer.toString(bd2));
             S.l29.setText(Integer.toString(bd3));
             S.l30.setText(r.format(prom7));
             S.l31.setText(Integer.toString(m1));
             S.l32.setText(Integer.toString(m2));
             S.l33.setText(Integer.toString(m3));
             S.l34.setText(r.format(prom8));
             S.l35.setText(Integer.toString(iuc1));
             S.l36.setText(Integer.toString(iuc2));
             S.l37.setText(Integer.toString(iuc3));
             S.l38.setText(r.format(prom9));
             //mostrar los promedios
             S.l39.setFont(new java.awt.Font("Arial", 1, 24));
             S.l40.setFont(new java.awt.Font("Arial", 1, 24));
             S.l41.setFont(new java.awt.Font("Arial", 1, 24));
             S.l42.setFont(new java.awt.Font("Arial", 1, 24));
             S.l39.setText(Float.toString(pp));
             S.l40.setText(Float.toString(ps));
             S.l41.setText(Float.toString(pt));
             S.l42.setText(Float.toString(pg));
             this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por utilizar el sistema");
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Escritorio().setVisible(true);   
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        t1.setText("");
        t2.setText("");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        t1.setText("");
        t2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Escritorio().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por utilizar el sistema");
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selección.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selección.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selección.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selección.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selección().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c10;
    private javax.swing.JComboBox<String> c11;
    private javax.swing.JComboBox<String> c12;
    private javax.swing.JComboBox<String> c13;
    private javax.swing.JComboBox<String> c14;
    private javax.swing.JComboBox<String> c15;
    private javax.swing.JComboBox<String> c16;
    private javax.swing.JComboBox<String> c17;
    private javax.swing.JComboBox<String> c18;
    private javax.swing.JComboBox<String> c19;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JComboBox<String> c20;
    private javax.swing.JComboBox<String> c21;
    private javax.swing.JComboBox<String> c22;
    private javax.swing.JComboBox<String> c23;
    private javax.swing.JComboBox<String> c24;
    private javax.swing.JComboBox<String> c25;
    private javax.swing.JComboBox<String> c26;
    private javax.swing.JComboBox<String> c27;
    private javax.swing.JComboBox<String> c3;
    private javax.swing.JComboBox<String> c4;
    private javax.swing.JComboBox<String> c5;
    private javax.swing.JComboBox<String> c6;
    private javax.swing.JComboBox<String> c7;
    private javax.swing.JComboBox<String> c8;
    private javax.swing.JComboBox<String> c9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
