
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author leonardo
 */
public class Semestre extends javax.swing.JFrame {

    /**
     * Creates new form Semestre
     */
    public Semestre() {
        initComponents();
        this.setSize(1310,710);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        l16 = new javax.swing.JLabel();
        l17 = new javax.swing.JLabel();
        l18 = new javax.swing.JLabel();
        l19 = new javax.swing.JLabel();
        l20 = new javax.swing.JLabel();
        l21 = new javax.swing.JLabel();
        l22 = new javax.swing.JLabel();
        l23 = new javax.swing.JLabel();
        l24 = new javax.swing.JLabel();
        l25 = new javax.swing.JLabel();
        l26 = new javax.swing.JLabel();
        l27 = new javax.swing.JLabel();
        l28 = new javax.swing.JLabel();
        l29 = new javax.swing.JLabel();
        l30 = new javax.swing.JLabel();
        l31 = new javax.swing.JLabel();
        l32 = new javax.swing.JLabel();
        l33 = new javax.swing.JLabel();
        l34 = new javax.swing.JLabel();
        l35 = new javax.swing.JLabel();
        l36 = new javax.swing.JLabel();
        l37 = new javax.swing.JLabel();
        l38 = new javax.swing.JLabel();
        l39 = new javax.swing.JLabel();
        l40 = new javax.swing.JLabel();
        l41 = new javax.swing.JLabel();
        l42 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre del alumno:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(570, 110, 270, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boleta.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 0, 400, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numero de boleta:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 120, 250, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Materia");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 170, 120, 29);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Orientacion Juvenil  y Profesional III");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 210, 450, 29);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Derecho II");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 250, 150, 29);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Programacion Orientada a Objetos");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 300, 440, 29);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contabilidad III");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 340, 210, 29);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Calculo Integral");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 380, 220, 29);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ingles V");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 420, 140, 29);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Base de datos");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 460, 200, 29);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Microeconomía");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 510, 210, 29);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Interaccion usuario computadora");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 550, 420, 29);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Calificación 1");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(560, 150, 170, 29);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Calificacion 2");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(770, 150, 170, 29);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Calificacion 3");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(970, 150, 170, 29);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Promedio");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(1180, 150, 140, 29);

        l1.setBackground(new java.awt.Color(51, 255, 51));
        l1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(l1);
        l1.setBounds(830, 110, 180, 23);

        l2.setBackground(new java.awt.Color(0, 255, 0));
        l2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(l2);
        l2.setBounds(270, 130, 180, 23);

        l3.setBackground(new java.awt.Color(255, 0, 0));
        l3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l3);
        l3.setBounds(610, 220, 60, 20);

        l4.setBackground(new java.awt.Color(255, 0, 0));
        l4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l4);
        l4.setBounds(820, 220, 60, 20);

        l5.setBackground(new java.awt.Color(255, 0, 0));
        l5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l5);
        l5.setBounds(1030, 220, 60, 20);

        l6.setBackground(new java.awt.Color(255, 0, 0));
        l6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l6);
        l6.setBounds(1210, 220, 60, 20);

        l7.setBackground(new java.awt.Color(255, 0, 0));
        l7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l7);
        l7.setBounds(610, 260, 60, 20);

        l8.setBackground(new java.awt.Color(255, 0, 0));
        l8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l8);
        l8.setBounds(820, 260, 60, 20);

        l9.setBackground(new java.awt.Color(255, 0, 0));
        l9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l9);
        l9.setBounds(1030, 260, 60, 20);

        l10.setBackground(new java.awt.Color(255, 0, 0));
        l10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l10);
        l10.setBounds(1210, 260, 60, 20);

        l11.setBackground(new java.awt.Color(255, 0, 0));
        l11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l11);
        l11.setBounds(610, 300, 60, 20);

        l12.setBackground(new java.awt.Color(255, 0, 0));
        l12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l12);
        l12.setBounds(820, 300, 60, 20);

        l13.setBackground(new java.awt.Color(255, 0, 0));
        l13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l13);
        l13.setBounds(1030, 300, 60, 20);

        l14.setBackground(new java.awt.Color(255, 0, 0));
        l14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l14);
        l14.setBounds(1210, 300, 60, 20);

        l15.setBackground(new java.awt.Color(255, 0, 0));
        l15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l15);
        l15.setBounds(610, 340, 60, 20);

        l16.setBackground(new java.awt.Color(255, 0, 0));
        l16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l16);
        l16.setBounds(820, 340, 60, 20);

        l17.setBackground(new java.awt.Color(255, 0, 0));
        l17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l17);
        l17.setBounds(1030, 340, 60, 20);

        l18.setBackground(new java.awt.Color(255, 0, 0));
        l18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l18);
        l18.setBounds(1210, 340, 60, 20);

        l19.setBackground(new java.awt.Color(255, 0, 0));
        l19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l19);
        l19.setBounds(610, 380, 60, 20);

        l20.setBackground(new java.awt.Color(255, 0, 0));
        l20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l20);
        l20.setBounds(820, 380, 60, 20);

        l21.setBackground(new java.awt.Color(255, 0, 0));
        l21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l21);
        l21.setBounds(1030, 380, 60, 20);

        l22.setBackground(new java.awt.Color(255, 0, 0));
        l22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l22);
        l22.setBounds(1210, 380, 60, 20);

        l23.setBackground(new java.awt.Color(255, 0, 0));
        l23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l23);
        l23.setBounds(610, 430, 60, 20);

        l24.setBackground(new java.awt.Color(255, 0, 0));
        l24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l24);
        l24.setBounds(820, 430, 60, 20);

        l25.setBackground(new java.awt.Color(255, 0, 0));
        l25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l25);
        l25.setBounds(1030, 430, 60, 20);

        l26.setBackground(new java.awt.Color(255, 0, 0));
        l26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l26);
        l26.setBounds(1210, 430, 60, 20);

        l27.setBackground(new java.awt.Color(255, 0, 0));
        l27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l27);
        l27.setBounds(610, 470, 60, 20);

        l28.setBackground(new java.awt.Color(255, 0, 0));
        l28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l28);
        l28.setBounds(820, 470, 60, 20);

        l29.setBackground(new java.awt.Color(255, 0, 0));
        l29.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l29);
        l29.setBounds(1030, 470, 60, 20);

        l30.setBackground(new java.awt.Color(255, 0, 0));
        l30.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l30);
        l30.setBounds(1210, 470, 60, 20);

        l31.setBackground(new java.awt.Color(255, 0, 0));
        l31.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l31);
        l31.setBounds(610, 520, 60, 20);

        l32.setBackground(new java.awt.Color(255, 0, 0));
        l32.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l32);
        l32.setBounds(820, 520, 60, 20);

        l33.setBackground(new java.awt.Color(255, 0, 0));
        l33.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l33);
        l33.setBounds(1030, 520, 60, 20);

        l34.setBackground(new java.awt.Color(255, 0, 0));
        l34.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l34);
        l34.setBounds(1210, 520, 60, 20);

        l35.setBackground(new java.awt.Color(255, 0, 0));
        l35.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l35);
        l35.setBounds(610, 560, 60, 20);

        l36.setBackground(new java.awt.Color(255, 0, 0));
        l36.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l36);
        l36.setBounds(820, 560, 60, 20);

        l37.setBackground(new java.awt.Color(255, 0, 0));
        l37.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l37);
        l37.setBounds(1030, 560, 60, 20);

        l38.setBackground(new java.awt.Color(255, 0, 0));
        l38.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(l38);
        l38.setBounds(1210, 560, 60, 20);
        getContentPane().add(l39);
        l39.setBounds(590, 610, 60, 40);
        getContentPane().add(l40);
        l40.setBounds(800, 610, 60, 40);
        getContentPane().add(l41);
        l41.setBounds(1010, 610, 60, 40);
        getContentPane().add(l42);
        l42.setBounds(1220, 610, 60, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 620, 40, 33);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("5° Semestre");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(870, 50, 230, 29);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Informatica");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(870, 10, 220, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Promedios");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 610, 130, 50);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boles.png"))); // NOI18N
        getContentPane().add(jLabel22);
        jLabel22.setBounds(70, 0, 100, 100);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 600, 1310, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calificacion2.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -20, 1310, 680);

        jMenu1.setText("Opciones");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x.png"))); // NOI18N
        jMenuItem1.setText("Cerrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por utilizar el sistema");
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por utilizar el sistema");
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Semestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Semestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Semestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Semestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Semestre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    javax.swing.JLabel l1;
    javax.swing.JLabel l10;
    javax.swing.JLabel l11;
    javax.swing.JLabel l12;
    javax.swing.JLabel l13;
    javax.swing.JLabel l14;
    javax.swing.JLabel l15;
    javax.swing.JLabel l16;
    javax.swing.JLabel l17;
    javax.swing.JLabel l18;
    javax.swing.JLabel l19;
    javax.swing.JLabel l2;
    javax.swing.JLabel l20;
    javax.swing.JLabel l21;
    javax.swing.JLabel l22;
    javax.swing.JLabel l23;
    javax.swing.JLabel l24;
    javax.swing.JLabel l25;
    javax.swing.JLabel l26;
    javax.swing.JLabel l27;
    javax.swing.JLabel l28;
    javax.swing.JLabel l29;
    public javax.swing.JLabel l3;
    javax.swing.JLabel l30;
    javax.swing.JLabel l31;
    javax.swing.JLabel l32;
    javax.swing.JLabel l33;
    javax.swing.JLabel l34;
    javax.swing.JLabel l35;
    javax.swing.JLabel l36;
    javax.swing.JLabel l37;
    javax.swing.JLabel l38;
    javax.swing.JLabel l39;
    javax.swing.JLabel l4;
    javax.swing.JLabel l40;
    javax.swing.JLabel l41;
    javax.swing.JLabel l42;
    javax.swing.JLabel l5;
    javax.swing.JLabel l6;
    javax.swing.JLabel l7;
    javax.swing.JLabel l8;
    javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables
}
